import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies
import java.io.File

class KoverConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            with(pluginManager) {
                apply("org.jetbrains.kotlinx.kover")
            }

            extensions.configure<KoverProjectExtension> {
                currentProject {
                    dependencies {
                        subprojects.forEach {
                            project(it.path)
                        }
                        createVariant("custom") {
                            add("devDebug", optional = true)
                            add("debug", optional = true)
                            add("jvm", optional = true)
                        }
                    }
                }

                reports {
                    // Make the ci/cd pipeline happy by providing the reports in the same folder as jacoco would
                    variant("custom") {
                        val reportsBaseDir = "${target.rootDir}/${target.name}/build/reports/jacoco"

                        xml {
                            xmlFile.set(File("$reportsBaseDir/kover/coverage.xml"))
                        }
                        html {
                            htmlDir.set(File("$reportsBaseDir/kover/html"))
                        }
                    }

                    filters {
                        includes {
                            packages("*.domain.usecase.implementation")
                        }
                        excludes {
                            androidGeneratedClasses()
                            // Exclude all classes generated by Dagger Hilt in JVM modules
                            classes(
                                "*_HiltComponents*",
                                "*_HiltModules*",
                                "*_HiltInjector*",
                                "*_GeneratedInjector*",
                                "*_HiltViewModelFactory*",
                                "dagger.hilt.*",
                                "hilt_aggregated_deps.*",
                                "*_*Factory*",
                                "*_MembersInjector",
                                "*.HiltWrapper_*",
                            )
                        }
                    }
                }
            }
        }
    }
}
